# download and install the Game Engine libraries, since they are not available in Maven Central (yet?)
before_install:
  - mkdir temp
  - cd temp
  - wget https://github.com/TinusTinus/game-engine/releases/download/game-engine-parent-2.1/game-engine-parent-2.1.pom
  - mvn install:install-file -Dpackaging=pom -Dfile=game-engine-parent-2.1.pom -DpomFile=game-engine-parent-2.1.pom
  - wget https://github.com/TinusTinus/game-engine/releases/download/game-engine-parent-2.1/game-engine-2.1.jar
  - mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=game-engine-2.1.jar
  - wget https://github.com/TinusTinus/game-engine/releases/download/game-engine-parent-2.1/game-engine-jinput-2.1.jar
  - mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=game-engine-jinput-2.1.jar
  - cd ..

language: java

jdk:
  - oraclejdk8